# -*- coding: utf-8 -*-
"""modello_16canali_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k4C89Hyo7ZRKtN4F9eyGDY-9V-dGr4WA

# Classificazione multiclasse (7 lesioni) — dataset MicroNIR ridotto a 16 canali

**Pipeline completa:**
1. Transfer calibration a range: MicroNIR 125 canali → 16 canali (tutto il dataset)
2. Training e confronto di tre modelli classici: SVM, Random Forest, XGBoost

Le 7 classi sono fortemente sbilanciate (ACK 296 … MEL 6), quindi:
- split **stratificato** train/test,
- `class_weight='balanced'` dove disponibile,
- metriche adatte: **balanced accuracy** e **F1 macro**, più matrice di confusione.

**File necessario:** `Databrief.xls` (foglio `Base`).

## 1) Transfer calibration a range: 125 → 16 canali (tutto il dataset)
"""

import pandas as pd
import numpy as np

# --- caricamento 125 canali ---
df = pd.read_excel('Databrief.xls', sheet_name='Base')
meta_cols = ['N','Sample','Class','yClass']
wl_cols = [c for c in df.columns if c not in meta_cols]
wl = np.array([float(c) for c in wl_cols])

# --- 16 canali: (nome, centro, lambda_min, lambda_max) ---
channel_ranges = [
    ('pixel_1',920,905,935),('pixel_2',955,940,970),('pixel_3',980,965,995),
    ('pixel_4',1020,995,1045),('pixel_5',1070,1045,1095),('pixel_6',1130,1100,1160),
    ('pixel_7',1195,1170,1220),('pixel_8',1260,1230,1290),('pixel_9',1310,1285,1335),
    ('pixel_10',1370,1345,1395),('pixel_11',1420,1400,1440),('pixel_12',1455,1435,1475),
    ('pixel_13',1500,1475,1525),('pixel_14',1560,1530,1590),('pixel_15',1620,1590,1650),
    ('pixel_16',1665,1650,1680),
]

# --- conversione a range su TUTTE le classi ---
X_full = df[wl_cols].to_numpy(float)
data16 = df[meta_cols].copy()
for name,centro,lo,hi in channel_ranges:
    mask = (wl>=lo)&(wl<=hi)
    data16[name] = X_full[:,mask].mean(axis=1)

ch = [c[0] for c in channel_ranges]
print("Dataset 16 canali:", data16.shape, "| NaN:", data16[ch].isna().sum().sum())
print(data16['Class'].value_counts())
data16.to_excel('dataset_completo_16canali.xlsx', index=False)

"""## 2) Preparazione dati per il training"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

X = data16[ch].values          # 16 feature
y = data16['Class'].values     # etichetta lesione

le = LabelEncoder()
y_enc = le.fit_transform(y)
print("Classi:", list(le.classes_))

# split stratificato (mantiene le proporzioni delle classi in train e test)
X_train, X_test, y_train, y_test = train_test_split(
    X, y_enc, test_size=0.25, stratify=y_enc, random_state=42)
print("Train:", X_train.shape, " Test:", X_test.shape)

"""## 3) Training e confronto: SVM, Random Forest, XGBoost"""

from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import balanced_accuracy_score, f1_score, accuracy_score
import xgboost as xgb

modelli = {
    'SVM': Pipeline([('scaler', StandardScaler()),
                     ('clf', SVC(kernel='rbf', class_weight='balanced', random_state=42))]),
    'Random Forest': RandomForestClassifier(n_estimators=300, class_weight='balanced',
                                            random_state=42),
    'XGBoost': xgb.XGBClassifier(n_estimators=300, max_depth=4, learning_rate=0.1,
                                 random_state=42, eval_metric='mlogloss'),
}

risultati = {}
for nome, modello in modelli.items():
    modello.fit(X_train, y_train)
    pred = modello.predict(X_test)
    risultati[nome] = {
        'accuracy'    : accuracy_score(y_test, pred),
        'bal_accuracy': balanced_accuracy_score(y_test, pred),
        'f1_macro'    : f1_score(y_test, pred, average='macro'),
        'pred'        : pred,
        'modello'     : modello,
    }
    print(f"{nome:15s}  acc={risultati[nome]['accuracy']:.3f}  "
          f"bal_acc={risultati[nome]['bal_accuracy']:.3f}  "
          f"f1_macro={risultati[nome]['f1_macro']:.3f}")

"""## 4) Report dettagliato e matrice di confusione del modello migliore"""

from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# scelgo il modello con la balanced accuracy piu' alta
best = max(risultati, key=lambda k: risultati[k]['bal_accuracy'])
print(f"Modello migliore (balanced accuracy): {best}\n")

pred = risultati[best]['pred']
print(classification_report(y_test, pred, target_names=le.classes_, zero_division=0))

cm = confusion_matrix(y_test, pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=le.classes_)
fig, ax = plt.subplots(figsize=(7,6))
disp.plot(ax=ax, cmap='Blues', xticks_rotation=45, colorbar=False)
ax.set_title(f'Matrice di confusione — {best}')
plt.tight_layout()
plt.show()

"""## 5) Validazione incrociata stratificata (stima più robusta)"""

from sklearn.model_selection import cross_val_score, StratifiedKFold

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
print("Balanced accuracy in 5-fold CV (media ± dev.std):\n")
for nome, modello in modelli.items():
    scores = cross_val_score(modello, X, y_enc, cv=cv, scoring='balanced_accuracy')
    print(f"  {nome:15s}  {scores.mean():.3f} ± {scores.std():.3f}")

"""## 6) Download del dataset a 16 canali"""

from google.colab import files
files.download('dataset_completo_16canali.xlsx')